a<-mean(DatosProyecto$TrumpENC, na.rm=TRUE)
b<-mean(DatosProyecto$ClintonENC, na.rm=TRUE)
c<-mean(DatosProyecto$OtroENC, na.rm=TRUE)
d<-mean(DatosProyecto$TrumpRes, na.rm=TRUE)
e<-mean(DatosProyecto$ClintonRes, na.rm=TRUE)
f<-mean(DatosProyecto$OtroRes, na.rm=TRUE)
g<-mean(DatosProyecto$Blancos, na.rm=TRUE)
h<-mean(DatosProyecto$Negros, na.rm=TRUE)
i<-mean(DatosProyecto$Hispanos, na.rm=TRUE)
j<-mean(DatosProyecto$Otros, na.rm=TRUE)
paste("Media encuesta Trump = ", a, sep=" ")
paste("Media encuesta Clinton = ", b, sep=" ")
paste("Media encuesta Otros Candidatos = ", c, sep=" ")
paste("Media resultados Trump = ", d, sep=" ")
paste("Media resultados Clinton = ", e, sep=" ")
paste("Media resultados Otros Candidatos = ", f, sep=" ")
paste("Media población Blancos = ", g, sep=" ")
paste("Media población Negros = ", h, sep=" ")
paste("Media población Hispanos = ", i, sep=" ")
paste("Media población Otros = ", j, sep=" ")
k<-sd(DatosProyecto$TrumpENC, na.rm=TRUE)
l<-sd(DatosProyecto$ClintonENC, na.rm=TRUE)
m<-sd(DatosProyecto$OtroENC, na.rm=TRUE)
n<-sd(DatosProyecto$TrumpRes, na.rm=TRUE)
o<-sd(DatosProyecto$ClintonRes, na.rm=TRUE)
p<-sd(DatosProyecto$OtroRes, na.rm=TRUE)
q<-sd(DatosProyecto$Blancos, na.rm=TRUE)
r<-sd(DatosProyecto$Negros, na.rm=TRUE)
s<-sd(DatosProyecto$Hispanos, na.rm=TRUE)
t<-sd(DatosProyecto$Otros, na.rm=TRUE)
paste("Desviación Estandar encuesta Trump = ", k, sep=" ")
paste("Desviación Estandar encuesta Clinton = ", l, sep=" ")
paste("Desviación Estandar encuesta Otros Candidatos = ", m, sep=" ")
paste("Desviación Estandar resultados Trump = ", n, sep=" ")
paste("Desviación Estandar resultados Clinton = ", o, sep=" ")
paste("Desviación Estandar resultados Otros Candidatos = ", p, sep=" ")
paste("Desviación Estandar población Blancos = ", q, sep=" ")
paste("Desviación Estandar población Negros = ", r, sep=" ")
paste("Desviación Estandar población Hispanos = ", s, sep=" ")
paste("Desviación Estandar población Otros = ", t, sep=" ")
paste("Distribución normal por estados encuesta Trump = ", rnorm(17, a,k), sep=" ")
paste("Distribución normal por estados encuesta Clinton = ", rnorm(17, b,l), sep=" ")
paste("Distribución normal por estados encuesta Otros Candidatos = ", rnorm(17, c,m), sep=" ")
paste("Distribución normal por estados resultado Trump = ", rnorm(17, d,n), sep=" ")
paste("Distribución normal por estados resultado Clinton= ", rnorm(17, e,o), sep=" ")
paste("Distribución normal por estados resultado Otros Candidatos = ", rnorm(17, f,p), sep=" ")
paste("Distribución normal por estados población Blancos = ", rnorm(17, g,q), sep=" ")
paste("Distribución normal por estados población Negros = ", rnorm(17, h,r), sep=" ")
paste("Distribución normal por estados población Hispanos = ", rnorm(17, i,s), sep=" ")
paste("Distribución normal por estados población Otros = ", rnorm(17, j,t), sep=" ")

